version: '3'
services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    network_mode: "host"
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      - "ADVERTISED_HOST=0.0.0.0"
      - "ADVERTISED_PORT=9092"

  producer:
    image: jvillete/kafka_producer:latest
    container_name: producer
    network_mode: "host"
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - kafka

  consumer:
    image: jvillete/kafka_consumer:latest
    container_name: consumer
    network_mode: "host"
    restart: on-failure
    depends_on:
      - kafka
      - producer
